language: python
sudo: false

python:
  - 3.6

install:
  - pip install flake8 black

script:
  - flake8 scrapy_link_filter/ --statistics
  - black -S -l 100 --target-version py36 scrapy_link_filter/
